language: python

sudo: required

services:
  - docker
  
python:
  - "3.6"

branches:
  only:
  - sync

before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"
  - git clone --branch=master https://$USERNAME:$GH_TOKEN@$GH_REF sync-mirror
  - cd sync-mirror
  - chmod +x commit.sh

stages:
  - sync
  - export
  - trigger




jobs:
  include:
    - stage: sync
      script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n kubernetes-helm
        - ./commit.sh
    - script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n google-containers
        - ./commit.sh
    - script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n cloud-solutions-images
        - ./commit.sh
    - script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n heptio-images
        - ./commit.sh
    - script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n k8s-artifacts-prod
        - ./commit.sh
    - script:
        - python sync.py -u $HUB_NAME -p $HUB_PWD -o $HUB_ORG -n kubernetes-e2e-test-images
        - ./commit.sh
    - stage: export
      script:
        - python sync.py -u $HUB_NAME -o $HUB_ORG --markdown-only
        - ./commit.sh

    - stage: trigger
      script:
        - python sync.py -u $HUB_NAME --travis-continue
        - ./commit.sh

      
